### ISSUE TITLE
Update OSC LDAP servers

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_auth_registration#18]
These servers:

https://github.com/OSC/ood_auth_registration/blob/9e7f6fe924bbeb0d1d9a344ea0449da887e4082e/ldap.php#L27-L28

need to be updated to:

```php
    'primary'         => 'ldaps://openldap1.infra.osc.edu',
    'fallback'        => 'ldaps://openldap2.infra.osc.edu',
```

**Comment by basilgohar** [comment]
For the new LDAP server, we no longer need to specify the port in the connection string?

**Comment by nickjer** [comment]
It is implied by `ldaps://` much like `443` is implied by `https://`
