### ISSUE TITLE
Users can't logout

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_auth_registration#5]
A user who logs into CILogon and is presented with the Registration page is unable to logout to re-authenticate with another account. The user is forced to register in order to logout.

**Comment by brianmcmichael** [comment]
This issue is also described in https://github.com/AweSim-OSC/osc-ondemand/issues/133

**Comment by ericfranz** [comment]
Add a "Logout" link in the menu in the top right corner. Logout URL be `/oidc?logout=https%3A%2F%2Fondemand.osc.edu` where the "logout" query param is actually the base url of the register page that we want to go back to. Perhaps the Logout URL should be a config option in the PHP config too.

**Comment by brianmcmichael** [comment]
Logout button added at https://github.com/OSC/ood_auth_registration/pull/9
